application: disease-tracker
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static/(.*\.ttf)
  static_files: static/\1
  upload: static/(.*\.ttf)
  mime_type: application/x-font-ttf

- url: /static
  static_dir: static


- url: /index.html
  script: main.app

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

